### ISSUE TITLE
cjs runs before mjs always

### ISSUE THREAD

**Issue by mafintosh** [holepunchto/bare-module#5]
running into this ordering issue

have 3 files

```
// dep.mjs
console.log('dep.mjs')
```

```
// dep.cjs
console.log('dep.cjs')
```

```
// main.mjs
import './dep.mjs'
import './dep.cjs'
```

running this prints

```
dep.cjs
dep.mjs
```

would expect the opposite

**Comment by kasperisager** [comment]
I see what the issue is: When imported from `.mjs`, `.cjs` modules are eagerly evaluated during module instantiation and so will run before any `.mjs` modules are evaluated _after_ module instantiation. We must instead defer evaluation of `.cjs` modules when imported from `.mjs` modules.
