### ISSUE TITLE
Module / Addon Not found.

### ISSUE THREAD

**Issue by n9lsjr** [holepunchto/bare-module#6]
Not sure if this is the correct repo but the trace seem to indicate Module class so here we go. I am trying to require Hyperswarm in to Bare running on expo-Android 

![image](https://github.com/holepunchto/bare-module/assets/64911460/b0e27e6b-81b3-4860-b66d-8a4331c8d34d)

but the app get stuck at this error.

![image](https://github.com/holepunchto/bare-module/assets/64911460/3ebcf0a8-fa2d-43df-bde0-b46f170efe52)

Maybe I am doing something wrong? Do I need to prebuildify that Module somehow?

**Comment by n9lsjr** [comment]
After further investigation it seems like this `resolution` here is undefined. I will post any progress if I can make it work 👍 

https://github.com/holepunchto/bare/blob/main/src/addon.js#L114

**Comment by kasperisager** [comment]
You most likely haven't linked the native addons. There's a PR here that adds autolinking to the Expo example: https://github.com/holepunchto/pear-expo-hello-world/pull/6

**Comment by n9lsjr** [comment]
Ah I missed that one. Thanks king 👍 💯
